### ISSUE TITLE
少了原生插件，根本运行不了

### ISSUE THREAD

**Issue by wukuy** [yooge/robot#7]
15:48:53.986 [JS Framework] 当前运行的基座不包含原生插件[AliCloud-NirvanaPns]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座
15:48:54.007 [JS Framework] 当前运行的基座不包含原生插件[Robot]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座

**Comment by yooge** [comment]
请按照文档操作，或者去群里问其他人

**Comment by langshen** [comment]
文档上的吕作没有引入或下载原生插件【Robot】啊。。
而且群也进不了，进几天了，群主都没通过。哎

**Comment by fkkfl** [comment]
没有原生插件

**Comment by chinapzw** [comment]
> 2.安装调试的apk
> robot-tools init

-----正在下载(大小:30M)
D:\JSON\autojs-vue-main\node_modules\request\request.js:458
    return self.emit('error', new Error('Invalid protocol: ' + protocol))
                              ^
我的是这样
Error: Invalid protocol: 127.0.0.1:
    at Request.init (D:\JSON\autojs-vue-main\node_modules\request\request.js:458:31)
    at new Request (D:\JSON\autojs-vue-main\node_modules\request\request.js:127:8)
    at request (D:\JSON\autojs-vue-main\node_modules\request\index.js:53:10)
    at downloadFile (D:\JSON\autojs-vue-main\node_modules\robot-tools\install_apk.js:8:5)
    at startDowload (D:\JSON\autojs-vue-main\node_modules\robot-tools\install_apk.js:19:5)
    at D:\JSON\autojs-vue-main\node_modules\robot-tools\install_apk.js:48:9

**Comment by chengyanggitHub** [comment]
也是缺少Robot插件

**Comment by clittlesea** [comment]
我也是 缺少Robot插件 进群也没同意

**Comment by vnool** [comment]
> 文档上的吕作没有引入或下载原生插件【Robot】啊。。 而且群也进不了，进几天了，群主都没通过。哎

执行 npm i robot-tool

**Comment by vnool** [comment]
> 我也是 缺少Robot插件 进群也没同意

群容易满， 改这个吧 862460452
